### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by pierol** [liyasthomas/postwoman#327] opened 2019-11-22 21:36 UTC
**Describe the bug**
Trying to build the package on Windows 10 machine with 

`npm run build`

```dos
WARNING in ./node_modules/yargs-parser/index.js 539:21-48
Critical dependency: the request of a dependency is an expression
 @ ./assets/js/curlparser.js
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&
 @ ./pages/index.vue?vue&type=script&lang=js&
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./layouts/default.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '../.postwoman/version.json' in 'R:\Sites\opensource\postwoman-master\layouts'
 @ ./layouts/default.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&) 284:0-54 316:19-34
 @ ./layouts/default.vue?vue&type=script&lang=js&
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

 FATAL  Nuxt build error                                                                                      22:29:04

  at WebpackBundler.webpackCompile (node_modules\@nuxt\webpack\dist\webpack.js:5314:21)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:5263:5)
  at async Builder.build (node_modules\@nuxt\builder\dist\builder.js:5597:5)
  at async Generator.initiate (node_modules\@nuxt\generator\dist\generator.js:70:7)
  at async Generator.generate (node_modules\@nuxt\generator\dist\generator.js:40:5)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-build.js:96:7)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-command.js:2575:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postwoman@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the postwoman@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\piero\AppData\Roaming\npm-cache\_logs\2019-11-22T21_29_04_067Z-debug.log
```
**To Reproduce**

Steps to reproduce the behavior (npm version 6.12.0, node version 12.13.0, SO Windows 10 1909):
1. Download the ZIP and unzip it
2. from inside the project folder run `npm install`
3. `npm run build`

**Comment by liyasthomas** [comment] 2019-11-22 23:20
Oh! That seems critical then. Let us investigate what went wrong and get back to you ASAP.
Thanks for reporting.

**Comment by liyasthomas** [comment] 2019-11-23 02:55
I just built the project on Windows platform and everything seems to be working 😕
![Capture](https://user-images.githubusercontent.com/10395817/69471940-a4f07b80-0dca-11ea-83f6-48b37f3547aa.PNG)

**Comment by pierol** [comment] 2019-11-23 09:41
I tried with a fresh install but the problem persist
![Untitled](https://user-images.githubusercontent.com/433875/69476721-d757a400-0ddd-11ea-8a7c-a4ec023343cb.jpg)

**Comment by liyasthomas** [comment] 2019-11-23 09:44
Can you do a `npm run dev` and let me know.

**Comment by pierol** [comment] 2019-11-23 09:47
![Untitled](https://user-images.githubusercontent.com/433875/69476782-af1c7500-0dde-11ea-811e-872bb54fca86.jpg)
![Untitled-02](https://user-images.githubusercontent.com/433875/69476783-afb50b80-0dde-11ea-82fd-6ce0bf433a80.jpg)

**Comment by liyasthomas** [comment] 2019-11-23 09:52
Check the root directory and if there exists a folder named `.postwoman` delete it. And again run `npm run dev`

**Comment by pierol** [comment] 2019-11-23 09:55
![Untitled](https://user-images.githubusercontent.com/433875/69476891-cc9e0e80-0ddf-11ea-848a-640c6bd865ff.jpg)

**Comment by liyasthomas** [comment] 2019-11-23 09:57
I'll run some more tests and get back to you.

**Comment by FatDoge** [comment] 2019-11-25 05:37
I meet the same problem, delete the ```.postwoman``` directory seems useless.
System infomation: ```Linux VM_202_150_centos 3.10.0-514.21.1.el7.x86_64```
I use the  cloud server offered by Tencent Cloud.

**Comment by liyasthomas** [comment] 2019-11-25 05:42
Issue has been identified. Will patch soon with a fix.

**Comment by FatDoge** [comment] 2019-11-25 06:08
```.postwoman/version.json``` file is not normally generated in ```build.js```. if you need to use it urgently, you can delete the corresponding import statement and the related code in ```layout/default.vue``` file first.(**Unrecommended**)

**Comment by SickoOrange** [comment] 2019-11-25 13:24
ths, please fix it cause i met also some issue like this.
or give me s solution to avoid this

**Comment by liyasthomas** [comment] 2019-11-25 13:55
We couldn't reproduce the issue at our end.

**Comment by hosseinnedaee** [comment] 2019-11-25 16:21
`npm run generate` and `npm run build` woks for me on Ubuntu 18.04

**Comment by liyasthomas** [comment] 2019-11-25 16:24
Our CI build is on Linux and it's working fine.
I can also confirm `npm run generate` works on Windows build 1803.

**Comment by FatDoge** [comment] 2019-11-26 00:44
I just clone the code to my pc again.
``` shell
> git clone https://github.com/liyasthomas/postwoman.git
> cd postwoman
> npm i
> npm run build
```
And everything is okay now...
Below is some information of my local enviroment:
``` shell
> nvm version
1.1.7
> node -v
v12.0.0
> npm -v
v6.10.3
```
My PC OS is Windows10 Home Chinese Edition 1903.

---
That's weird, I can't repoduce the problem and I want to know why, I even change the local PC date to yestoday.
**I will try again on my linux server and let us see if there is something strange.**

**Comment by liyasthomas** [comment] 2019-11-26 00:48
Usually these kinda errors happen when npm cache exists with lower version of dependencies. Delete node_modules, clean the cache, npm install again will solve most of it.

**Comment by liyasthomas** [comment] 2019-11-26 01:29
Some workarounds:

0. Delete node_modules
1. `npm cache clean`
2. `npm i`
3. `npm run dev` or `npm run generate`

If the above steps fails, try:
0. `npm rebuild node-sass`
1. `npm run generate`

**Comment by NBTX** [comment] 2019-11-26 15:03
@liyasthomas I think this can be closed?

**Comment by liyasthomas** [comment] 2019-11-26 15:06
This issue is stale and hence closing

**Comment by ccenjie** [comment] 2019-12-19 06:36
so , how to let it work, i do not see any solution,


Delete node_modules
npm cache clean
npm i
npm run dev or npm run generate
If the above steps fails, try:

npm rebuild node-sass
npm run generate


i do that, but no work

**Comment by liyasthomas** [comment] 2019-12-19 06:37
Is the error log as same as mentioned in this issue?

**Comment by NBTX** [comment] 2019-12-19 11:03
Just noticed in this case it may be because they downloaded a zip of the project rather than using git clone.

I believe the build script relies on the directory being a git repository in order to obtain certain information, so the project needs to be cloned rather than a ZIP file simply downloaded.

If I'm right though, I can just update the build script to accommodate this.

**Comment by liyasthomas** [comment] 2019-12-19 11:11
@NBTX `build.js` is tailored for CI, remove git dependencies  / online version fetch and if possible, get version from `package.json`. Or else, completely comment out version section from footer. 👍

**Comment by AndrewBastin** [comment] 2020-02-09 05:07
Closing this issue as it seems to be fixed.

**Closed by AndrewBastin** 2020-02-09 05:07 UTC
Labels: bug, need information

**Comment by Cedric4real** [comment] 2020-02-20 15:05
Cloning definetely solves the issue, thank you.
