### ISSUE TITLE
Add compatibility for postman collections & environments

### ISSUE THREAD

**Issue by AFRI4N** [liyasthomas/postwoman#746] opened 2020-04-07 14:57 UTC
**Is your feature request related to a problem? Please describe.**
My team is working with postman. Therefore, I have to work with collections and environment variables that are created and optimized for postman. However, to use them in postwoman I have to replace `{{variable}}` to `<<variable>>` for postwoman as well as it dosn't set the requestUrls correct. For example the requestUrl `{{variable}}/validate` maps into `{{variable}}` in postwoman.

**Describe the solution you'd like**
Support postman environments or supporting {{}} variable definitions
Adapt/Fix request URL Import

**Describe alternatives you've considered**
Changes everything manually. However this takes a bit of time and the product owners don't like that (ofc)

**Additional context**
![grafik](https://user-images.githubusercontent.com/50735002/78684518-d9378500-78f0-11ea-85d8-f8986a7c57c0.png)

**Comment by liyasthomas** [comment] 2020-04-13 01:09
Duplicate of #759

**Closed by liyasthomas** 2020-04-13 01:09 UTC
Labels: enhancement
