### ISSUE TITLE
Module not found: Error: Can't resolve '../.postwoman/version.json'

### ISSUE THREAD

**Issue by chnzhang** [liyasthomas/postwoman#457] opened 2019-12-24 08:20 UTC
npm install
npm run dev 
error
in ./layouts/default.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '../.postwoman/version.json' in 'D:\GitHub\postwoman\layouts'

![image](https://user-images.githubusercontent.com/3386915/71402988-518f7880-2669-11ea-9882-9b1665e89405.png)

**Comment by liyasthomas** [comment] 2019-12-24 08:37
Possible duplicate of #327

**Closed by liyasthomas** 2019-12-24 08:37 UTC
