### ISSUE TITLE
can not build

### ISSUE THREAD

**Issue by hylun** [liyasthomas/postwoman#444] opened 2019-12-19 10:38 UTC
I found such an error when run 'nuxt build'

ERROR in ./layouts/default.vue?vue&type=script&lang=js& (./node_modules/_babel-loader@8.0.6@babel-loader/lib??ref--2-0!./node_modules/_vue-loader@15.8.3@vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '../.postwoman/version.json' in '/home/wwwroot/postwoman-1.0.0/layouts'
 @ ./layouts/default.vue?vue&type=script&lang=js& (./node_modules/_babel-loader@8.0.6@babel-loader/lib??ref--2-0!./node_modules/_vue-loader@15.8.3@vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&) 168:0-54 197:19-34
 @ ./layouts/default.vue?vue&type=script&lang=js&
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

**Comment by liyasthomas** [comment] 2019-12-19 10:44
Possible duplicate of #327 
Try this fixes: https://github.com/liyasthomas/postwoman/issues/327#issuecomment-558417184

**Comment by liyasthomas** [comment] 2019-12-19 11:01
I just did a clean `git clone` and everything seems to be working fine.

**Comment by liyasthomas** [comment] 2019-12-19 11:13
Closing this issue in favor of #327 . Track issue there.

**Closed by liyasthomas** 2019-12-19 11:13 UTC
Labels: invalid
