### ISSUE TITLE
Cannot use localhost as base url

### ISSUE THREAD

**Issue by profran** [liyasthomas/postwoman#56] opened 2019-08-25 00:36 UTC
**Describe the bug**
Unable to use 'localhost' as base url.

**To Reproduce**
1. Go to https://liyasthomas.github.io/postwoman/
2. Click on URL field
3. Type in: http://localhost:3002 (any port will do, I just happen to have a Node.js server running on that port)
4. Send button is disabled

**Expected behavior**
I expect the Send button to be enabled

**Desktop (please complete the following information):**
 - OS: Arch Linux (64-bit)
 - Browser: Chromium
 - Version: 75.0.3770.142 (Official Build)

**Additional context**
I cloned the repo and I think the issue is related to pages/index.vue line 247 on urlNotValid's validation pattern, I changed the return statement to always be false, and the problem was solved.

**Comment by liyasthomas** [comment] 2019-08-25 00:47
This might be a possibile duplicate of #2 
Its a restriction due to the CORS (Cross Origin Request Policy), there isn't a client side work around to this unless the host your trying to access should respond with the appropriate CORS headers.
Please refer to docs here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
Quick solution is to use a HTTPS API host, which supports CORS

**Comment by profran** [comment] 2019-08-25 00:57
I first thought of that, but my Node.js API is configured to support CORS requests. I'm sure it's just the URL validation's pattern which expects an URL with a domain at the end (any_url + .com .co .ar .jp ...). I'll see if I can open a PR to solve the problem tomorrow.

**Comment by liyasthomas** [comment] 2019-08-25 00:59
If that's the case, I'll surely look into it. You're welcomed to open a PR to fix it.

**Comment by NBTX** [comment] 2019-08-25 01:23
Ah yes, I know the issue, I had to mess with the regex to get websockets to work. I'll see if I can find some more permissive ones - and I'll add in IP addresses.

**Comment by liyasthomas** [comment] 2019-08-25 01:26
You could've opted to use two regex for URLValidation()  🤭

**Comment by NBTX** [comment] 2019-08-25 01:31
Yes, that was probably how I'd do it.

That said - is validation even necessary? Perhaps it would be ideal to just show an error if it fails to connect, like the websockets do, then to handle each edge case in regexes?

**Comment by liyasthomas** [comment] 2019-08-25 01:33
Sooner or later, URL validation will be necessary. Anyway let's discuss.

**Comment by NBTX** [comment] 2019-08-25 01:35
Okay. I'll update the url validation to include the two regex checks in the mean time.

**Comment by liyasthomas** [comment] 2019-08-25 02:16
@NBTX sendRequest() isn't firing. Can you check changes on URL validation

**Comment by NBTX** [comment] 2019-08-25 13:27
Solved by #52

**Closed** 2019-08-25 13:40 UTC
Labels: bug, need testing
