### ISSUE TITLE
POSTing large raw JSON packets

### ISSUE THREAD

**Issue by AtomicNicos** [liyasthomas/postwoman#265] opened 2019-11-04 12:57 UTC
**Describe the bug**
Given huge packets, PW throws a URI too long HTTP error, and won't finish the request.

**To Reproduce**
1. Have an endpoint that can receive a request (node + JS, other).
2. On PW send POST with RAW input, with excess of 4000 characters or so.
3. Send.

**Expected behavior**
Should POST without error.

**Suggested fixes**
- Send content as raw bytes in request body, as per the Volley API and others.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Opera | Chrome | Firefox | Edge
 - Version *latest*

**Additional context**
Trying to test my own API with heavy loads,  PW can't handle it for the moment, sadly.

**Comment by penguindustin** [comment] 2019-11-28 01:11
Just tried a POST to an endpoint with 6000+ and 12K+ chars and couldn't reproduce. Are you still having this issue?

**Comment by liyasthomas** [comment] 2019-11-28 01:14
@AtomicNicos have you tried reproducing the issue after #292 ? If issue is is fixed, feel free to this.

**Comment by liyasthomas** [comment] 2019-12-01 05:23
https://stackoverflow.com/questions/55631057/axios-post-data-as-form-data-instead-of-as-json-in-payload

**Comment by liyasthomas** [comment] 2019-12-14 16:48
From https://stackoverflow.com/questions/2891574/how-do-i-resolve-a-http-414-request-uri-too-long-error it is clearly evident that this error is a  limitation from the server side and got nothing to do with PW - hence closing the issue.

**Closed by liyasthomas** 2019-12-14 16:48 UTC
Labels: bug, help wanted
