### ISSUE TITLE
I can't send POST method

### ISSUE THREAD

**Issue by turbobin** [liyasthomas/postwoman#210] opened 2019-10-24 06:19 UTC
hi,
I meet a strange problem,  when I choose POST method to send, it always turn on OPTIONS, why ? look at the image:

![image](https://user-images.githubusercontent.com/35211343/67458328-7fa40c80-f668-11e9-888a-8ca6ee17e296.png)

**Comment by liyasthomas** [comment] 2019-10-24 07:02
@turbobin Thanks for reporting the bug. Sorry for the inconveniences caused. Could you please share the API endpoints so that we could run some manual tests.

**Comment by NBTX** [comment] 2019-10-25 12:16
The `OPTIONS` request being sent first is a CORS preflight request that gets made automatically when `POST`ing data to a server. The `POST` request doesn't get sent as the `OPTIONS` preflight request is failing.

This is a 'feature' of the browser that we have no control over, so this issue will require use of the Postwoman proxy.

**Comment by NBTX** [comment] 2019-10-25 12:19
Also @liyasthomas we could perhaps try and detect this (for the purposes of prompting the user to turn on the proxy) by sending our own preflight request *first* if the proxy is turned off (i.e. just making a request to `OPTIONS`) - we'd get an 'opaque' response but it would be enough to know it's going to fail and therefore know that we need to prompt the user with a message.

**Comment by liyasthomas** [comment] 2019-10-25 12:22
Thats doable. Now we detect allow Access-Control-Allow-Origin: * to detect whether CORS occur or not. Think we could op for this method instead.

**Comment by liyasthomas** [comment] 2019-11-07 07:18
Closing this issues since it's a possible duplicate of #274

**Closed by liyasthomas** 2019-11-07 07:18 UTC
Labels: need information, need testing
