### ISSUE TITLE
Create standalone vue components of the request builder.

### ISSUE THREAD

**Issue by Jefwillems** [liyasthomas/postwoman#474] opened 2020-01-04 14:19 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to integrate postwoman in a website i'm building. The website allows users to create a request and use it for later. Part of the functionality is building the request, for which i'd like to integrate postwoman (and save the built request in localStorage or something like that.

**Describe the solution you'd like**
A vue component that can be embedded into my vue site. e.g, point to it with a route with vue-router, and binding a value to the built request with v-model.

**Describe alternatives you've considered**
Until now i'm building something similar, but i feel like this would be an easier approach.

**Comment by liyasthomas** [comment] 2020-01-04 14:21
Possible duplicate of #384

**Comment by liyasthomas** [comment] 2020-01-04 14:21
Please consider contributing to the project for resolving this issue 🙌🏼

**Closed by liyasthomas** 2020-01-04 14:21 UTC

**Comment by Jefwillems** [comment] 2020-01-04 14:25
Hmm now that i read that issue again it seems we want similar things. I'll hook into that thread and try to contribute
