### ISSUE TITLE
A question that has been raised but not resolved

### ISSUE THREAD

**Issue by VKingi** [liyasthomas/postwoman#658] opened 2020-03-11 08:56 UTC
Linux: CentOS Linux release 7.7.1908 (Core), nodejs: v12.16.1
windows:10.0.14393,nodejs: v12.13.1
> On both platforms, the same error occurs.
> I found that there were many people who had the same problem as me, but I found that the real problem was not solved.

#### Text:
~~~
ERROR in ./layouts/default.vue?vue&type=script&lang=js& (./node_modules/babel-lo                                  ader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/d                                  efault.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '../.postwoman/version.json' in '/root/po                                  stwoman-1.9.0/layouts'
 @ ./layouts/default.vue?vue&type=script&lang=js& (./node_modules/babel-loader/l                                  ib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default                                  .vue?vue&type=script&lang=js&) 676:0-54 745:19-34
 @ ./layouts/default.vue?vue&type=script&lang=js&
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
~~~
#### IMG:
![image](https://user-images.githubusercontent.com/16144561/76398636-2db21800-63b8-11ea-8be8-b436d7581ebe.png)
Ask the community to help me,thanks

**Comment by liyasthomas** [comment] 2020-03-11 09:08
#651 

Possible root cause of this issue:

> When you download the repo as `zip`, you just download the source files of the most recent commit of the default branch. Essentially, when you download you can’t make use of any git commands, you can’t view the commit messages, you are just not using git at all. We need `version.json` file which depends on `git version tags` found in `.git` directory.

Solution: Instead of downloading the zip and starting the server, try cloning `https://github.com/liyasthomas/postwoman.git`. Now the version number is correctly fetching from package.json and release tag, so I think I should this issue.

Feel free to close this issue if you were able to fix this.

**Closed** 2020-03-11 17:36 UTC
