### ISSUE TITLE
On Save Update existing API

### ISSUE THREAD

**Issue by sheecegardezi** [liyasthomas/postwoman#204] opened 2019-10-22 12:33 UTC
**Is your feature request related to a problem? Please describe.**
As I am developing my API is evolving. When I make a change in api I have to save the API again and delete the old saved version. 
 
**Describe the solution you'd like**
When I press ctrl+s (or some other shortcut) save action is triggered.
A background logic checks if I had saved this API before or not.

If its already saved:
      -promote to update existing API
       -update the changes I have made in the existing API 
else:
   -promote to save a new API
   -save the new API 
 
**Describe alternatives you've considered**
With each change save a new API and delete the old one from the collection.

**Comment by liyasthomas** [comment] 2019-10-22 16:54
Collections feature has just been shipped! Thanks for the first set of suggestions. Will surely consider adding these feature requests in near future.

In the meantime, you can make use of 'Edit request' feature within collection/folder/ to update API changes. Expecting new feature requests and suggestions as well as bug reports 🙌🏼

**Comment by liyasthomas** [comment] 2019-10-22 17:06
Btw, if the request is already saved, saving again it will ask you to update the existing API. This is already implemented.
Alternatively, if you want to save the API as a new one, please choose another collection or folder to save it as a new entry. This is also available right now.

Let me know if you're facing any bugs.

**Comment by liyasthomas** [comment] 2019-10-24 13:59
#209 fixes this, hence closing.

**Comment by sheecegardezi** [comment] 2019-10-31 12:28
![step1-run a request](https://user-images.githubusercontent.com/7543039/67946664-eb244600-fc35-11e9-800b-35f8c6d63e02.png)
![step2-create collection and folder](https://user-images.githubusercontent.com/7543039/67946663-ea8baf80-fc35-11e9-98e2-fae0bb37069c.png)
![step3-save the request as test 1](https://user-images.githubusercontent.com/7543039/67946662-ea8baf80-fc35-11e9-904a-d49aa1da6642.png)
![step4-the request is saved as expected](https://user-images.githubusercontent.com/7543039/67946661-ea8baf80-fc35-11e9-8525-7f3f831005ad.png)
![step5-make some changes to api and press save](https://user-images.githubusercontent.com/7543039/67946666-eb244600-fc35-11e9-9878-098446d33cea.png)
![step6-a new request got saved rahter then updating the existing one](https://user-images.githubusercontent.com/7543039/67946665-eb244600-fc35-11e9-9f1f-ac2b0c505a0a.png)

**Comment by liyasthomas** [comment] 2019-10-31 12:31
Work around:
step 6:select test request (already saved from step 5) and save

**Comment by sheecegardezi** [comment] 2019-10-31 12:33
Thank you, I was selecting the collection the folder but not the request :D
Cheers,

**Comment by cortopy** [comment] 2020-01-23 12:47
I'm also experiencing this issue. I just can't make it work so that I update an existing request. I click on the request itself, click on save (nothing happens), refresh and the new details do not appear

**Comment by liyasthomas** [comment] 2020-01-23 13:13
@cortopy can you please explain excatly what is not working at your end?

**Comment by cortopy** [comment] 2020-01-23 14:48
sure! thanks for the prompt reply @liyasthomas 

I'm having a hard time updating saved requests. After reading this issue, this is what I've tried:

1. Save my request
2. Click on the Saved Request to make sure that's the one I'm editing
3. Make some changes
4. Click on the Save button (nothing happens)
5. I refresh browser
6. I get the request as in (1) but the new changes are not there

**Comment by liyasthomas** [comment] 2020-01-23 15:01
First of all sorry for the inconveniences. I admit saving request are a bit of cumbersome.

Here's what I did to reproduce the issue:
1. Made a request
2. Saved it to Collection
3. Made few changes to request
4. Clicked on save > choose my previous Collection > (same folder and same request) > Save
5. Imported last saved request by clicking

**Comment by liyasthomas** [comment] 2020-03-09 17:44
Closing due to inactivity

**Closed by liyasthomas** 2020-03-09 17:44 UTC
Labels: enhancement, help wanted
