### ISSUE TITLE
npm run dev module was not found: ../.postwoman/version.json

### ISSUE THREAD

**Issue by ccenjie** [liyasthomas/postwoman#442] opened 2019-12-19 04:07 UTC
i sure that i do npm install && npm run dev

but it does not work

throw a err :

 WARN  Compiled with 1 warnings                       friendly-errors 12:00:18

 WARN  in ./node_modules/yargs-parser/index.js        friendly-errors 12:00:18

Critical dependency: the request of a dependency is an expression
                                                      friendly-errors 12:00:18

 ERROR  Failed to compile with 1 errors               friendly-errors 12:00:18

This relative module was not found:                   friendly-errors 12:00:18
                                                      friendly-errors 12:00:18
* ../.postwoman/version.json in ./node_modules/babel-loader/lib??ref--2-0!./nod
_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=scri
t&lang=js&
i Waiting for file changes                                            12:00:18
i Memory usage: 208 MB (RSS: 358 MB)                                  12:00:18

**Comment by liyasthomas** [comment] 2019-12-19 04:08
Duplicate of #327

**Closed by liyasthomas** 2019-12-19 04:08 UTC
