### ISSUE TITLE
websocket url to long  browser got stuck

### ISSUE THREAD

**Issue by zibber2015** [liyasthomas/postwoman#677] opened 2020-03-17 10:19 UTC
**Desktop**
 - OS: mac10.14.6
 - Browser: chrome
 - Version:docker 1.9.0

```
ws://127.0.0.1:17001/action?token=05d3aa444233a13b3254eeff495a5138&some=
```

**Comment by liyasthomas** [comment] 2020-03-17 11:02
How to reproduce the issue?
Possible duplicate of #471

**Closed** 2020-03-17 22:29 UTC
Labels: invalid, need information
