### ISSUE TITLE
Import/Export collections from private github repos to share among teams.

### ISSUE THREAD

**Issue by manjitkumar** [liyasthomas/postwoman#867] opened 2020-05-12 13:52 UTC
**Is your feature request related to a problem? Please describe.**
I want to make collections version-controlled and shareable among teams from Github. Alternatively, If we can have roles permission and collections on the cloud with postwoman as a service.

**Describe the solution you'd like**
User should be able to sync their collections with another team member, using Github roles/permission on the synced repository. 

**Describe alternatives you've considered**
One can always take an export and upload it to their repo as a JSON file to keep versioning maintained. The goal is to reuse Github's version control and roles/permissions and to avoid manually updating collections by exporting and importing.

**Comment by liyasthomas** [comment] 2020-05-12 14:03
Possible duplicate of #580 which will also cover roles and permissions for collections.

**Closed** 2020-05-12 14:02 UTC
