### ISSUE TITLE
* ../.postwoman/version.json in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&        friendly-errors 11:12:37  

### ISSUE THREAD

**Issue by 13619633937lw** [liyasthomas/postwoman#448] opened 2019-12-20 03:13 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by liyasthomas** [comment] 2019-12-20 03:15
Duplicate of #327

**Closed by liyasthomas** 2019-12-20 03:15 UTC
