### ISSUE TITLE
Shall we have the team management ability and some public documents?

### ISSUE THREAD

**Issue by zhangzhaohong** [liyasthomas/postwoman#1014] opened 2020-07-22 12:41 UTC
Do you have the ability to mange one team? So that anyone of the members in the team can read the public documents. We hope to make a group and a public document group, anyone of the group can read the  documents in the public document group.

**Comment by liyasthomas** [comment] 2020-07-22 12:51
Please check the current open issues before creating another issue. Duplicate of #580

**Closed by liyasthomas** 2020-07-22 12:51 UTC
